apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: scheduling.kcp.io
spec:
  latestResourceSchemas:
  - v221006-eaaf199d.locations.scheduling.kcp.io
  - v221212-cf67ac73a.placements.scheduling.kcp.io
  maximalPermissionPolicy:
    local: {}
status: {}
