apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: apiresource.kcp.io
spec:
  latestResourceSchemas:
  - v220628-546034da.apiresourceimports.apiresource.kcp.io
  - v220628-546034da.negotiatedapiresources.apiresource.kcp.io
  maximalPermissionPolicy:
    local: {}
status: {}
