apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: topology.kcp.dev
spec:
  latestResourceSchemas:
  - v221115-9b370eb8.partitions.topology.kcp.dev
  - v221118-9364e75c.partitionsets.topology.kcp.dev
status: {}
