apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  annotations:
    bootstrap.kcp.dev/create-only: "true"
    bootstrap.kcp.dev/battery: root-compute-workspace
    extra.apis.kcp.dev/compute.workload.kcp.dev: "true"
  name: kubernetes
spec:
  latestResourceSchemas:
  - v124.ingresses.networking.k8s.io
  - v124.services.core
  - v124.deployments.apps
  maximalPermissionPolicy:
    local: {}
status: {}
