apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kcp:apiexport:workload:maximal-permission-policy
rules:
- apiGroups: ["workload.kcp.io"]
  verbs: ["*"]
  resources:
  - synctargets
  - synctargets/status # changed by the syncer
